extends:
  ["https://unpkg.com/@stoplight/spectral-owasp-ruleset/dist/ruleset.mjs"]

# Downgrade OWASP rules to warnings to prevent failures from external OGC schemas
# External schemas (schemas.opengis.net) don't comply with strict OWASP rules
# but are outside our control
rules:
  owasp:api4:2023-string-limit: warn
  owasp:api4:2023-string-restricted: warn
  owasp:api4:2023-array-limit: warn
  owasp:api4:2023-integer-limit: warn
  owasp:api4:2023-rate-limit: warn
  owasp:api4:2023-define-cors-origin: warn
