"""OpenAPI contract tests module.

Note on POST /items endpoint exclusion
======================================

The tests explicitly exclude POST /items endpoints due to a known issue with pygeoapi:

**Issue**: pygeoapi advertises POST endpoints for feature collections
(/collections/{collectionId}/items) in the OpenAPI schema even when the server
is NOT configured to support transactions (create/update/delete operations).

**Root Cause**: The OpenAPI schema generated by pygeoapi contains invalid JSON
Schema references (specifically: /$defs/propertyRef) in the request body
definition for these POST endpoints. This reference points to a schema
definition that does not exist in the OpenAPI document.

**Impact**: When schemathesis attempts to generate test cases for these endpoints,
it fails with:
    schemathesis.exceptions.SchemaError: Unresolvable JSON pointer in the
    schema: /$defs/propertyRef

**Workaround**: The tests use schema.include() filters to exclude POST /items
endpoints from contract testing. This allows all other endpoints (GET, OPTIONS,
DELETE, etc.) to be tested successfully while avoiding the invalid schema
references.

**Future**: This workaround can be removed once pygeoapi fixes the schema
generation for POST endpoints or properly excludes them when transactions
are not configured.

References:
- POST endpoints affected: /collections/{collectionId}/items (for all collections)
- Collections with issue: lakes, obs
"""

import os

import pytest
import schemathesis

schema_apikey = schemathesis.from_pytest_fixture("protected_apikey_schema")
schema_bearer = schemathesis.from_pytest_fixture("protected_bearer_schema")

# Filter out POST /items endpoints that have unresolvable schema references
# See module docstring for detailed explanation
schema_apikey.include(
    lambda op: not (op.method.upper() == "POST" and "/items" in op.path)
)
schema_bearer.include(
    lambda op: not (op.method.upper() == "POST" and "/items" in op.path)
)


@schema_apikey.parametrize()
def test_api_with_apikey(case):
    """Test the API with API-KEY protection."""
    if case.path_parameters:
        if case.path_parameters.get("jobId"):
            job_id = case.path_parameters.get("jobId")
            if r"\n" or r"\r" in job_id:
                case.path_parameters["jobId"] = job_id.strip()
            if "%0A" in job_id:
                case.path_parameters["jobId"] = job_id.replace("%0A", "")
            if "%0D" in job_id:
                case.path_parameters["jobId"] = job_id.replace("%0D", "")
    case.headers = {"X-API-KEY": "pygeoapi"}
    response = case.call()
    case.validate_response(response)


@pytest.mark.skipif(
    os.environ.get("JWKS_ENABLED", "").lower() not in ("true", "1"),
    reason="Skipping bearer token tests when JWKS is not enabled",
)
@schema_bearer.parametrize()
def test_api_with_bearer(case, access_token):
    """Test the API with Authorization Bearer token protection."""
    if case.path_parameters:
        if case.path_parameters.get("jobId"):
            job_id = case.path_parameters.get("jobId")
            if r"\n" or r"\r" in job_id:
                case.path_parameters["jobId"] = job_id.strip()
            if "%0A" in job_id:
                case.path_parameters["jobId"] = job_id.replace("%0A", "")
            if "%0D" in job_id:
                case.path_parameters["jobId"] = job_id.replace("%0D", "")
    case.headers = {"Authorization": f"Bearer {access_token}"}
    response = case.call()
    case.validate_response(response)
