# generated by datamodel-codegen:
#   filename:  pygeoapi-config-0.x.yml

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any

from pydantic import (
    AnyUrl,
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    constr,
)


class Bind(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    host: Annotated[str, Field(description='binding IP')]
    port: Annotated[int, Field(description='binding port')]


class OnExceed(Enum):
    error = 'error'
    throttle = 'throttle'


class Limits(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    max_items: Annotated[
        int | None,
        Field(
            description='maximum limit of items to return for item type providers', ge=1
        ),
    ] = 10
    default_items: Annotated[
        int | None,
        Field(
            description='default limit of items to return for item type providers', ge=1
        ),
    ] = 10
    max_distance_x: Annotated[
        float | None, Field(description='maximum distance in x for all data providers')
    ] = None
    max_distance_y: Annotated[
        float | None, Field(description='maximum distance in y for all data providers')
    ] = None
    max_distance_units: Annotated[
        str | None,
        Field(
            description='maximum distance units as per UCUM https://ucum.org/ucum#section-Tables-of-Terminal-Symbols'
        ),
    ] = None
    on_exceed: Annotated[
        OnExceed | None, Field(description='how to handle limit exceeding')
    ] = 'throttle'


class Templates(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    path: Annotated[
        str | None,
        Field(
            description='path to templates folder containing the Jinja2 template HTML files'
        ),
    ] = None
    static: Annotated[
        str | None,
        Field(
            description='path to static folder containing css, js, images and other static files referenced by the template'
        ),
    ] = None


class Map(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    url: Annotated[str, Field(description='URI template of tile server')]
    attribution: Annotated[str, Field(description='map attribution')]


class Manager(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    name: Annotated[
        str,
        Field(
            description='plugin name (see `pygeoapi.plugin` for supported process_managers)'
        ),
    ]
    connection: Annotated[
        str | dict[str, Any],
        Field(description='connection info to store jobs (e.g. filepath)'),
    ]
    output_dir: Annotated[
        str, Field(description='temporary file area for storing job results (files)')
    ]


class ApiRules(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    api_version: Annotated[
        str | None, Field(description='optional semantic API version number override')
    ] = None
    strict_slashes: Annotated[
        bool | None,
        Field(
            description='whether trailing slashes are allowed in URLs (disallow = True)'
        ),
    ] = None
    url_prefix: Annotated[
        str | None,
        Field(
            description='Set to include a prefix in the URL path (e.g. https://base.com/my_prefix/endpoint).\nPlease refer to the configuration section of the documentation for more info.'
        ),
    ] = None
    version_header: Annotated[
        str | None,
        Field(
            description='API version response header (leave empty or unset to omit this header)'
        ),
    ] = None


class Server(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    bind: Annotated[Bind, Field(description='binding server information')]
    url: Annotated[str, Field(description='URL of server (as used by client)')]
    icon: Annotated[
        str | None, Field(description='URL of favicon for default HTML customization')
    ] = None
    logo: Annotated[
        str | None,
        Field(description='URL of logo image for default HTML customization'),
    ] = None
    admin: Annotated[
        bool | None,
        Field(description='whether to enable the Admin API (default is false)'),
    ] = False
    mimetype: Annotated[str, Field(description='default MIME type')]
    encoding: Annotated[str, Field(description='default server encoding')]
    gzip: Annotated[
        bool | None,
        Field(
            description='default server config to gzip/compress responses to requests with gzip in the Accept-Encoding header'
        ),
    ] = None
    language: Annotated[str | None, Field(description='default server language')] = None
    languages: Annotated[list[str] | None, Field(description='supported languages')] = (
        None
    )
    locale_dir: Annotated[
        str | None, Field(description='directory of translations')
    ] = None
    cors: Annotated[
        bool | None, Field(description='boolean on whether server should support CORS')
    ] = False
    pretty_print: Annotated[
        bool | None,
        Field(description='whether JSON responses should be pretty-printed'),
    ] = False
    limit: Annotated[
        int | None,
        Field(description='limit of items to return.  DEPRECATED: use limits instead'),
    ] = 10
    limits: Annotated[
        Limits | None, Field(description='server level data limiting')
    ] = None
    templates: Annotated[
        Templates | None,
        Field(
            description='optional configuration to specify a different set of templates for HTML pages. Recommend using absolute paths. Omit this to use the default provided templates'
        ),
    ] = None
    map: Annotated[Map, Field(description='leaflet map setup for HTML pages')]
    ogc_schemas_location: Annotated[
        str | None, Field(description='local copy of http://schemas.opengis.net')
    ] = None
    manager: Annotated[
        Manager | None,
        Field(description='optional OGC API - Processes asynchronous job management'),
    ] = None
    api_rules: Annotated[
        ApiRules | None,
        Field(description='optional API design rules to which pygeoapi should adhere'),
    ] = None


class Broker(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    url: Annotated[AnyUrl, Field(description='URL of broker')]
    channel: Annotated[str | None, Field(description='channel to subscribe to')] = None
    hidden: Annotated[
        bool | None, Field(description='whether to hide broker link on API responses')
    ] = False


class Pubsub(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    name: Annotated[str, Field(description='name of pubsub client')]
    broker: Annotated[Broker, Field(description='broker definition')]


class Level(Enum):
    CRITICAL = 'CRITICAL'
    ERROR = 'ERROR'
    WARNING = 'WARNING'
    INFO = 'INFO'
    DEBUG = 'DEBUG'
    NOTSET = 'NOTSET'


class Mode(Enum):
    size = 'size'
    time = 'time'


class When(Enum):
    s = 's'
    m = 'm'
    h = 'h'
    d = 'd'
    w0_w6 = 'w0-w6'
    midnight = 'midnight'


class Rotation(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    mode: Annotated[Mode, Field(description='whether to rotate based on size or time')]
    when: Annotated[When | None, Field(description='type of interval')] = None
    interval: Annotated[
        int | None, Field(description='how often to rotate in time mode')
    ] = None
    max_bytes: Annotated[
        int | None, Field(description='when to rotate in size mode')
    ] = None
    backup_count: Annotated[
        int | None, Field(description='how many backups to keep')
    ] = None


class Logging(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    level: Annotated[
        Level,
        Field(
            description='The logging level (see https://docs.python.org/3/library/logging.html#logging-levels).\nIf level is defined and logfile is undefined, logging messages are output to the server’s stdout'
        ),
    ]
    logfile: Annotated[
        str | None, Field(description='the full file path to the logfile.')
    ] = None
    logformat: Annotated[str | None, Field(description='custom logging format')] = None
    dateformat: Annotated[
        str | None, Field(description='custom date format to use in logs')
    ] = None
    rotation: Annotated[Rotation | None, Field(description='log rotation settings')] = (
        None
    )


class KeywordsType(Enum):
    discipline = 'discipline'
    temporal = 'temporal'
    place = 'place'
    theme = 'theme'
    stratum = 'stratum'


class Contact(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    name: Annotated[str, Field(description='Lastname, Firstname')]
    position: Annotated[str | None, Field(description='position')] = None
    address: Annotated[str | None, Field(description='postal address')] = None
    city: Annotated[str | None, Field(description='city')] = None
    stateorprovince: Annotated[str | None, Field(description='administrative area')] = (
        None
    )
    postalcode: Annotated[str | None, Field(description='postal or ZIP code')] = None
    country: Annotated[str | None, Field(description='country')] = None
    phone: Annotated[str | None, Field(description='phone number')] = None
    fax: Annotated[str | None, Field(description='fax number')] = None
    email: Annotated[str | None, Field(description='email address')] = None
    url: Annotated[str | None, Field(description='URL of contact')] = None
    hours: Annotated[str | None, Field(description='hours of service')] = None
    instructions: Annotated[str | None, Field(description='contact instructions')] = (
        None
    )
    role: Annotated[
        str | None, Field(description='role as per the ISO 19115 CI_RoleCode codelist')
    ] = None


class Type(Enum):
    collection = 'collection'
    stac_collection = 'stac-collection'


class Visibility(Enum):
    default = 'default'
    hidden = 'hidden'


class LinkedData(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    context: Annotated[
        list[dict[constr(pattern=r'^.*$'), str | dict[str, Any]]] | None,
        Field(description='additional JSON-LD context'),
    ] = None


class Link(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    type: Annotated[str, Field(description='MIME type')]
    rel: Annotated[
        str,
        Field(
            description='link relations per https://www.iana.org/assignments/link-relations/link-relations.xhtml'
        ),
    ]
    title: Annotated[str | None, Field(description='title')] = None
    href: Annotated[str, Field(description='URL')]
    hreflang: Annotated[str | None, Field(description='language')] = None
    length: Annotated[
        int | None,
        Field(description='optional content size in bytes (e.g. for download links)'),
    ] = None


class Spatial(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    bbox: Annotated[
        list[float],
        Field(description='bounding box of resource', max_length=6, min_length=4),
    ]
    crs: Annotated[
        str | None, Field(description='coordinate reference system of bbox')
    ] = 'http://www.opengis.net/def/crs/OGC/1.3/CRS84'


class Temporal(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    begin: AwareDatetime | None = None
    end: AwareDatetime | None = None
    trs: Annotated[
        str | None, Field(description='temporal reference system of features')
    ] = 'http://www.opengis.net/def/uom/ISO-8601/0/Gregorian'
    resolution: Annotated[str | None, Field(description='temporal resolution')] = None
    default: Annotated[str | None, Field(description='default time value')] = None


class Extents(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    spatial: Annotated[Spatial, Field(description='spatial extent and CRS')]
    temporal: Annotated[
        Temporal | None, Field(description='temporal extent of resource')
    ] = None


class Limits1(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    max_items: Annotated[
        int | None,
        Field(
            description='maximum limit of items to return for item type providers', ge=1
        ),
    ] = 10
    default_items: Annotated[
        int | None,
        Field(
            description='default limit of items to return for item type providers', ge=1
        ),
    ] = 10
    max_distance_x: Annotated[
        float | None, Field(description='maximum distance in x for all data providers')
    ] = None
    max_distance_y: Annotated[
        float | None, Field(description='maximum distance in y for all data providers')
    ] = None
    max_distance_units: Annotated[
        str | None,
        Field(
            description='maximum distance units as per UCUM https://ucum.org/ucum#section-Tables-of-Terminal-Symbols'
        ),
    ] = None
    on_exceed: Annotated[
        OnExceed | None, Field(description='how to handle limit exceeding')
    ] = 'throttle'


class Type1(Enum):
    feature = 'feature'
    coverage = 'coverage'
    record = 'record'
    map = 'map'
    tile = 'tile'
    edr = 'edr'
    stac = 'stac'


class Geometry(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    x_field: Annotated[
        str, Field(description='the field corresponding to the x geometry')
    ]
    y_field: Annotated[
        str, Field(description='the field corresponding to the y geometry')
    ]


class Format(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    name: Annotated[str, Field(description='format name')]
    mimetype: Annotated[str, Field(description='format mimetype')]


class Formatter(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    name: Annotated[str, Field(description='name of formatter')]
    geom: Annotated[bool | None, Field(description='whether to include geometry')] = (
        True
    )
    attachment: Annotated[
        bool | None, Field(description='whether to provide as an attachment')
    ] = False


class Type2(Enum):
    process = 'process'


class Processor(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    name: Annotated[
        str,
        Field(
            description='see `pygeoapi.plugin` for supported provider names.\nFor custom built plugins, use the import path (e.g. `mypackage.provider.MyProvider`)'
        ),
    ]


class Resources1(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    type: Annotated[Type2 | None, Field(description='resource type')] = None
    processor: Annotated[Processor | None, Field(description='process binding')] = None
    allow_internal_requests: Annotated[
        bool | None, Field(description='whether to allow internal HTTP requests')
    ] = False


class I18nString1(RootModel[str]):
    root: str


class I18nString(
    RootModel[
        str
        | dict[constr(pattern=r'^[a-zA-Z]{2,3}([-_][a-zA-Z0-9]{2,3})?$'), I18nString1]
    ]
):
    root: (
        str
        | dict[constr(pattern=r'^[a-zA-Z]{2,3}([-_][a-zA-Z0-9]{2,3})?$'), I18nString1]
    )


class I18nArray1(RootModel[list[str]]):
    root: list[str]


class I18nArray(
    RootModel[
        list[str]
        | dict[constr(pattern=r'^[a-zA-Z]{2,3}([-_][a-zA-Z0-9]{2,3})?$'), I18nArray1]
    ]
):
    root: (
        list[str]
        | dict[constr(pattern=r'^[a-zA-Z]{2,3}([-_][a-zA-Z0-9]{2,3})?$'), I18nArray1]
    )


class Options(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    connect_timeout: int | None = None
    tcp_user_timeout: int | None = None
    keepalives: int | None = None
    keepalives_idle: int | None = None
    keepalives_count: int | None = None
    keepalives_interval: int | None = None
    pool_size: Annotated[
        int | None,
        Field(description='persistent connections held open per worker process'),
    ] = None
    max_overflow: Annotated[
        int | None,
        Field(description='extra short-lived connections allowed above pool_size'),
    ] = None
    pool_recycle: Annotated[
        int | None,
        Field(
            description='recreate connections older than this many seconds (-1 never recycles)'
        ),
    ] = None
    pool_timeout: Annotated[
        int | None,
        Field(
            description='seconds to wait for a connection from the pool before erroring'
        ),
    ] = None
    pool_pre_ping: Annotated[
        bool | None,
        Field(description='test connections with a lightweight ping before use'),
    ] = None


class Config(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    options: Options | None = None


class PostgreSQL(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    config: Config | None = None


class Provider2(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    PostgreSQL_1: Annotated[PostgreSQL | None, Field(alias='PostgreSQL')] = None


class Identification(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    title: Annotated[I18nString, Field(description='the title of the service')]
    description: Annotated[
        I18nString, Field(description='some descriptive text about the service')
    ]
    keywords: Annotated[
        I18nArray, Field(description='list of keywords about the service')
    ]
    keywords_type: Annotated[
        KeywordsType | None,
        Field(
            description='keyword type as per the ISO 19115 MD_KeywordTypeCode codelist'
        ),
    ] = None
    terms_of_service: Annotated[
        I18nString | None, Field(description='terms of service')
    ] = None
    url: Annotated[str, Field(description='informative URL about the service')]


class License(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    name: Annotated[I18nString, Field(description='licensing details')]
    url: Annotated[I18nString | None, Field(description='license URL')] = None


class Provider(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    name: Annotated[I18nString, Field(description='organization name')]
    url: Annotated[I18nString | None, Field(description='URL of provider')] = None


class Metadata(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    identification: Annotated[
        Identification, Field(description='server identification')
    ]
    license: Annotated[License, Field(description='licensing details')]
    provider: Annotated[Provider, Field(description='service provider details')]
    contact: Annotated[Contact, Field(description='service contact details')]


class Provider1(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    type: Annotated[Type1, Field(description='underlying data geospatial type')]
    default: Annotated[
        bool | None,
        Field(
            description='whether the provider is the default.  If not specified, the\nfirst provider definition is considered the default'
        ),
    ] = None
    name: Annotated[
        str,
        Field(
            description='see `pygeoapi.plugin` for supported provider names.\nFor custom built plugins, use the import path (e.g. `mypackage.provider.MyProvider`)'
        ),
    ]
    data: Annotated[
        str | dict[str, Any],
        Field(description='the data filesystem path or URL, depending on plugin setup'),
    ]
    editable: Annotated[
        bool | None, Field(description='whether the resource is editable')
    ] = False
    count: Annotated[
        bool | None,
        Field(description='whether to perform a count query for collection queries'),
    ] = True
    table: Annotated[
        str | None, Field(description='table name for RDBMS-based providers')
    ] = None
    id_field: Annotated[
        str | None,
        Field(
            description='required for vector data, the field corresponding to the ID'
        ),
    ] = None
    geometry: Annotated[
        Geometry | None, Field(description='the field corresponding to the geometry')
    ] = None
    time_field: Annotated[
        str | None,
        Field(
            description='optional field corresponding to the temporal property of the dataset'
        ),
    ] = None
    title_field: Annotated[
        str | None,
        Field(
            description='optional field of which property to display as title/label on HTML pages'
        ),
    ] = None
    format: Annotated[Format | None, Field(description='default format')] = None
    options: Annotated[
        Options | None,
        Field(
            description='optional options key value pairs to pass to provider (i.e. GDAL creation)'
        ),
    ] = None
    properties: Annotated[
        list[str] | None,
        Field(
            description='only return the following properties, in order', min_length=1
        ),
    ] = None
    crs: Annotated[
        list[AnyUrl] | None,
        Field(
            description='supported coordinate reference systems (CRSs).\npygeoapi will always provide or add the default if not specified.'
        ),
    ] = ['http://www.opengis.net/def/crs/OGC/1.3/CRS84']
    storage_crs: Annotated[
        AnyUrl | None,
        Field(
            description='the CRS identifier, from the list of supported CRS identifiers, that may be used to retrieve\nfeatures from a collection without the need to apply a CRS transformation.'
        ),
    ] = 'http://www.opengis.net/def/crs/OGC/1.3/CRS84'
    storage_crs_coordinate_epoch: Annotated[
        float | None,
        Field(
            description='point in time at which coordinates in the spatial feature collection are referenced to the dynamic\ncoordinate reference system in `storageCrs`, that may be used to retrieve features from a\ncollection without the need to apply a change of coordinate epoch. It is expressed as a decimal\nyear in the Gregorian calendar.',
            examples=['2017-03-25 in the Gregorian calendar is epoch 2017.23'],
        ),
    ] = None
    include_extra_query_parameters: Annotated[
        bool | None, Field(description='whether to include extra query parameters')
    ] = False


class Resources(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    type: Annotated[Type, Field(description='resource type')]
    visibility: Annotated[
        Visibility | None, Field(description='visibility state of the resource')
    ] = 'default'
    title: Annotated[I18nString, Field(description='the title of the service')]
    description: Annotated[
        I18nString, Field(description='some descriptive text about the service')
    ]
    keywords: Annotated[
        I18nArray, Field(description='list of keywords about the service')
    ]
    linked_data: Annotated[
        LinkedData | None,
        Field(alias='linked-data', description='linked data configuration'),
    ] = None
    links: Annotated[
        list[Link] | None, Field(description='list of related links', min_length=0)
    ] = None
    extents: Annotated[
        Extents,
        Field(
            description='spatial and temporal extents.  Note that adding custom named dimensions is also possible'
        ),
    ]
    limits: Annotated[
        Limits1 | None, Field(description='collection level data limiting')
    ] = None
    providers: Annotated[
        list[Provider1], Field(description='required connection information')
    ]
    formatters: Annotated[
        list[Formatter] | None,
        Field(description='custom formatters to apply to output'),
    ] = None


class PygeoapiConfigurationSchema(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    server: Annotated[Server, Field(description='server object')]
    pubsub: Annotated[
        Pubsub | None,
        Field(description='Pub/Sub settings for event driven notifications'),
    ] = None
    logging: Annotated[Logging, Field(description='logging definitions')]
    metadata: Annotated[Metadata, Field(description='server metadata')]
    resources: Annotated[
        dict[constr(pattern=r'^.*$'), Resources | Resources1],
        Field(description='collections or processes published by the server'),
    ]
